//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sCharacter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sCharacter()
        {
            this.xActivityCharacterN = new HashSet<xActivityCharacterN>();
        }
    
        public int IDsCharacter { get; set; }
        public string Name { get; set; }
        public string NameAlt { get; set; }
        public string Descr { get; set; }
        public string NameEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<xActivityCharacterN> xActivityCharacterN { get; set; }
    }
}
