//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sLoyaltyToLawGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sLoyaltyToLawGroup()
        {
            this.sLoyaltyToLaw = new HashSet<sLoyaltyToLaw>();
        }
    
        public int IDsLoyaltyToLawGroup { get; set; }
        public string NameSingle { get; set; }
        public string NamePlural { get; set; }
        public string Descr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sLoyaltyToLaw> sLoyaltyToLaw { get; set; }
    }
}
