//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCharacterDependence
    {
        public int chr { get; set; }
        public int dep { get; set; }
        public int sex { get; set; }
        public int beg { get; set; }
        public Nullable<int> end { get; set; }
        public Nullable<int> val { get; set; }
    }
}
