//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class xActivityDay
    {
        public int IDsActivity { get; set; }
        public int N { get; set; }
        public int Value { get; set; }
    
        public virtual sActivity sActivity { get; set; }
    }
}
