//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class xCharacterDependence
    {
        public int IDsCharacter { get; set; }
        public int IDsCharacterDependent { get; set; }
        public int IDsSex { get; set; }
        public int Points { get; set; }
        public Nullable<int> Value { get; set; }
        public int ID { get; set; }
    }
}
