//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dAngelCharacter
    {
        public int IDdAngel { get; set; }
        public int IDsCharacter { get; set; }
        public Nullable<int> Val { get; set; }
    
        public virtual dAngel dAngel { get; set; }
    }
}
