//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dAngelPracticeDayShift
    {
        public System.Guid IDdPracticeDay { get; set; }
        public int IDsCharacter { get; set; }
        public int Shift { get; set; }
    
        public virtual dAngelPracticeDay dAngelPracticeDay { get; set; }
    }
}
