//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sActivity()
        {
            this.xActivityDay = new HashSet<xActivityDay>();
            this.xActivityCharacterN = new HashSet<xActivityCharacterN>();
        }
    
        public int IDsActivity { get; set; }
        public string Name { get; set; }
        public int IDsActivityType { get; set; }
        public string Descr { get; set; }
        public string Code { get; set; }
    
        public virtual sActivityType sActivityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<xActivityDay> xActivityDay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<xActivityCharacterN> xActivityCharacterN { get; set; }
    }
}
